[PR] 주문 단건 조회 기능 구현
ITEM-BROWSER/ITEM-BROWSER pull request #1
Opened 2024-01-27 16:30 UTC by qkrtkdwns3410

1. 목표
- 주문 단건 조회 관련 기능 구현
2. 내용
-

2024-01-28 05:54 UTC, samuelmento requested changes
좋은 코드 감사합니다!

코드리뷰 남겨드립니다!

2024-01-28 05:54 UTC, samuelmento commented on src/test/java/com/psj/itembrowser/order/service/OrderSelectServiceTest.java
> +        //when
개행 부탁드립니다.

2024-01-28 05:54 UTC, samuelmento commented on src/main/java/com/psj/itembrowser/order/controller/OrderApiController.java
>  @RequestMapping("/v1/api/order")
복수로 표현 부탁드립니다. 
```java
/v1/api/orders
```

2024-01-28 05:54 UTC, samuelmento commented on src/main/java/com/psj/itembrowser/order/controller/OrderApiController.java
>  @RequestMapping("/v1/api/order")
추가적으로 v1과 같은 버전관리가 Controller 상단에 위치하면 나중에 버전관리하기가 어려울겁니다. 각 컨트롤러 API에서 작성하시는게 버전관리가 쉬울겁니다.

2024-01-28 05:54 UTC, samuelmento commented on src/main/java/com/psj/itembrowser/order/domain/dto/request/OrderRequestDTO.java
>      boolean shownDeletedOrder;
이렇게 필드값으로 관리하는 것이 좋아보이지는 않는데 다른 방법 없을지 고민됩니다.

2024-01-28 05:54 UTC, samuelmento commented on src/test/java/com/psj/itembrowser/order/service/OrderSelectServiceTest.java
> +        assertThat(result.getDeletedDate()).isEqualTo(validOrder.getDeletedDate());
assertThat 다음에 비교하는 비교군은 실 데이터 값이 들어가야합니다. given에서 만들어낸 변수로 넣게되면 비교하는 의미가 then쪽에서 없을 때가 많고 코드를 읽을때도 수정하는 부분에서 눈에 띄기가 쉽지 않습니다.

2024-01-31 07:44 UTC, ka-MS reviewed
고생하셨습니다! 코드 리뷰 쉽지 않네요

2024-01-31 07:44 UTC, ka-MS commented on src/main/java/com/psj/itembrowser/common/handler/ControllerAdvice.java
> +	@ExceptionHandler(CustomRuntimeException.class)
@ExceptionHandler(BadRequestException.class, IllegalStateException.class)
이런식으로 핸들러에 나열하는 방식은 어떤가요?

2024-01-31 07:44 UTC, ka-MS commented on src/main/java/com/psj/itembrowser/common/handler/ControllerAdvice.java
> +		return new ResponseEntity<>(apiError, e.getErrorCode().getStatus());
동일한 코드가 반복되는데 메소드로 빼는건 어떨까요?

2024-01-31 07:44 UTC, ka-MS commented on src/main/java/com/psj/itembrowser/order/domain/dto/request/OrderRequestDTO.java
> +	Boolean shownDeletedOrder = false;
필드의 접근제한자가 private이 아닌 defalut인 이유가 있을까요?

2024-01-31 11:38 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/common/handler/ControllerAdvice.java
> +	@ExceptionHandler(CustomRuntimeException.class)
저는 커스텀 에러코드를 핸들러에 전달하기위해서 별도 CustomRuntimeException 을 만들어서 사용했었습니다.
저 부분에서 만약에 BadRequestException.class, IllegalStateException.class 을 받으면 매개변수로 어떤 에러를 넣어줄것인지가 애매해지는데.. 혹시 그 부분은 어떻게 생각하시는지요

2024-01-31 11:43 UTC, qkrtkdwns3410 commented on src/test/java/com/psj/itembrowser/order/service/OrderSelectServiceTest.java
> +        //when
수정했습니다!

2024-01-31 11:43 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/order/controller/OrderApiController.java
>  @RequestMapping("/v1/api/order")
복수 표현 및 버전관리를 메서드 개별로 각각 선언으로 변경했습니다.

2024-01-31 11:46 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/common/handler/ControllerAdvice.java
> +		return new ResponseEntity<>(apiError, e.getErrorCode().getStatus());
저도 그게 나을거같네요!

2024-01-31 11:49 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/order/domain/dto/request/OrderRequestDTO.java
> +	Boolean shownDeletedOrder = false;
해당 부분은 누락으로 수정했습니다 감사합니다

2024-01-31 13:29 UTC, samuelmento commented on src/main/java/com/psj/itembrowser/common/handler/ControllerAdvice.java
> +		return new ResponseEntity<>(apiError, e.getErrorCode().getStatus());
우선 이 부분에 대해서는 따로 빼지 않는 것이 좋아보입니다. 

하나의 메서드안에서 처리가 n번 반복이 된다면 메서드나 클래스로 빼는 것을 고려해볼 수 있습니다.

이 경우, 각각의 핸들러에서 처리가 되는 로직이므로 반복으로 보기 어렵습니다.

2024-01-31 14:04 UTC, samuelmento requested changes
수고하셨습니다 ! 요청드린 부분 수정 부탁드릴게요!

2024-01-31 14:04 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/controller/OrderApiController.java
> +    }
@RequestParam 을 이용해서 하셔도 좋고 권한에 따라서 결과가 완전히 분리되어야 한다면

기존에
```java
private Boolean shownDeletedOrder = false;
```
위의 값을 필드로 DTO에서 관리하고 있는데,
여기서  Controller에서 권한 분기를 처리하시고 그에 맞게 Service 로직을 각각 호출해서 처리하면 더 좋아보입니다.

2024-01-31 14:04 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/domain/dto/request/OrderRequestDTO.java
> +	}
이 부분도 수정이 될 것 같습니다. 불필요해서 삭제 될 것을 기대합니다.

2024-01-31 14:04 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/domain/vo/Order.java
> +        order.ordererId = ordererNo;
이 부분 체크 한번 해보시고, No 말고 다른 표현을 적으시면 좋겠습니다.

2024-01-31 14:04 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/persistence/OrderPersistence.java
> +        return findOrder;
if문 전과 return 전에 개행 부탁드립니다.

2024-01-31 14:04 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/security/service/impl/UserDetailsServiceImpl.java
> +		return new CustomUserDetails(memberResponseDTO);
개행 이 부분 좀 더 신경써서 해주세요!

2024-01-31 14:04 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/security/service/impl/UserDetailsServiceImpl.java
> +		//QUESTION 스프링 예제에서는 상속을 받았지만, 상속받는 이유를 잘 모르겠다.
주석 불필요한 부분이면 삭제해주세요

2024-02-02 06:40 UTC, merged