[PR] 상품 정보 등록 및 수정  기능 구현
ITEM-BROWSER/ITEM-BROWSER pull request #4
Opened 2024-01-30 14:48 UTC by ka-MS

2024-01-31 04:10 UTC, qkrtkdwns3410 requested changes
등록 기능 전반에 대해 리뷰했습니다 고생하셨습니다 앞으로 더 고생하셔야죠 ㅋㅋ 🥲

2024-01-31 04:10 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/product/service/ProductService.java
> +    ProductResponseDTO getProduct(Long productId) throws NotFoundException;
NotFoundException을 서비스단에서 던져주는 이유가 있는지 궁금해요! 서비스단에서 에러를 처리할 수 있지 않나요?🤔

2024-01-31 04:10 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/product/service/impl/ProductServiceImpl.java
> +        }
1. 요 부분은.. 별도 검증 클래스로 빼거나 도메인안에서 검증했으면 좋겠습니다. 
- Product 도메인안에서 LocalDateTime 시작일과 종료일을 각각 매개변수로 받아서 검증하는 방법(Static 사용?)
- 아니면 ProductValidation 클래스를 만드는 방법이 있을 것 같습니다.
2. productRequestDTO 안의 LocalDateTime 이 만약 NULL 값으로 들어오게되면 아마 NPE 가 발생하여 서비스 로직에 문제가 생길 수 도 있을 것 같습니다.

2024-01-31 04:10 UTC, qkrtkdwns3410 commented on src/main/resources/schema.sql
> +    `IMG_URL`             varchar(500) NOT NULL COMMENT '이미지 URL',
(프론트단에서 이미지 URL 을 전송받게 되는 걸까요?, 아니면 임시 URL인가요)

2024-01-31 04:10 UTC, qkrtkdwns3410 commented on src/main/resources/schema.sql
> +    `UPDATED_DATE`        timestamp   NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '업데이트일',
👍

2024-01-31 04:10 UTC, qkrtkdwns3410 commented on src/main/resources/sqlmap/com/psj/itembrowser/product-mapper.xml
> +  </select>
foreach open과 close 코드스타일 통일을 하는게 어떨 까 싶습니다.

2024-01-31 04:10 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/product/service/impl/ProductServiceImpl.java
> +    public ProductResponseDTO getProduct(Long productId) throws NotFoundException {
요 부분도

2024-01-31 04:16 UTC, qkrtkdwns3410 requested changes

2024-01-31 04:16 UTC, qkrtkdwns3410 commented on src/main/resources/schema.sql
> +    `UPDATED_DATE`        timestamp   NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '업데이트일',
ON UPDATE CURRENT_TIMESTAMP👍

2024-01-31 04:16 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/common/exception/ErrorCode.java
> +    PRODUCT_VALIDATE_FAIL(HttpStatus.BAD_REQUEST, "PRODUCT_004","Validation Error"),
, "PRODUCT_004","Validation Error" 스페이스 부탁드립니다

2024-01-31 08:03 UTC, ka-MS commented on src/main/resources/schema.sql
> +    `IMG_URL`             varchar(500) NOT NULL COMMENT '이미지 URL',
임시로 Url로 해놓은 상태인데 스토리지에 저장하는 형태로 바꿀 계획입니다.

2024-01-31 08:19 UTC, ka-MS commented on src/main/java/com/psj/itembrowser/product/service/ProductService.java
> +    ProductResponseDTO getProduct(Long productId) throws NotFoundException;
기존에 작성되어 있던 부분인데 **서비스단에서 에러를 처리**란건 Persistence 영역에서의 처리를 말씀하시는걸까요?
확인해보니 org.apache.ibatis.javassist.NotFoundException; 이 사용되어 checkedexception으로 처리 되고 있었습니다. 
custom NotFoundException으로 바꾸고 persistence 영역에서 처리되도록 수정했습니다!

2024-01-31 12:33 UTC, samuelmento commented on src/main/java/com/psj/itembrowser/product/domain/vo/ProductImage.java
> +    private String imgUrl;
1. MultipartFile 을 기준으로 값을 받게됩니다. 
2. S3에 설정해둔 secretKey 값을 기준으로 처리가 됩니다. 
3. key 값을 알아야 나중에 찾아올 수 있습니다.
4. path 정보를 알고있어야합니다.
5. key, path를 저장해야 합니다. 

url은 return이고 key, path를 저장해야합니다.

2024-01-31 13:02 UTC, samuelmento requested changes
고생하셨습니다 ! 조금 더 달려보시죠!

2024-01-31 13:02 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/common/handler/ControllerAdvice.java
> +    }
논의 해보시고 결정사항 공유 부탁드립니다!

2024-01-31 13:02 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/product/controller/ProductApiController.java
> +    }
생성 로직에 있어서는 id 값이 기준이 될 수 없겠죠. 생성 전이니까 create가 안되서 id 모르죠

반대로 put 같이 update를 해야하는 경우는 id 알 수 있습니다. 

식별은 어떻게 할 것인가.
```java
@PutMapping("/v1/api/products/{productId}")
```
```java
@PutMapping("/v1/api/products/{id}")
```
@RequestParam을 이용하게 되면 더 RestFul한 API를 개발할 수 있습니다.

2024-01-31 13:02 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/product/persistence/ProductPersistence.java
> +    public void addProductImages(List<ProductImage> productImages) {
add의 표현은 list, set과 같이 자료구조에 값을 더할때 쓰는 용어로 개발용어가 강력합니다.

그렇기 때문에 create 생성과 관련된 단어를 쓰시는게 좋아보입니다. 

productRepository.save(product)

create가 커질 경우, Factory Service로 빼서 처리하시는게 좋습니다. (DDD)

2024-01-31 13:02 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/product/service/impl/ProductServiceImpl.java
> +    public void addProduct(ProductRequestDTO productRequestDTO) {
createProduct로 변경부탁드립니다.

2024-01-31 13:02 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/product/service/impl/ProductServiceImpl.java
> +        List<ProductImage> productImages = productRequestDTO.getProductImages();
RequestDTO에서 image를 url로 저장하지 못할겁니다. 
이 사이에 S3에 저장하는 로직이 필요합니다.

2024-01-31 13:02 UTC, samuelmento commented on src/main/java/com/psj/itembrowser/product/service/impl/ProductServiceImpl.java
> +        productPersistence.addProductImages(productImages);
```java
    @Override
    @Transactional(readOnly = false)
    public void addProduct(ProductRequestDTO productRequestDTO) {
        List<ProductImage> productImages = productRequestDTO.getProductImages();

        if (productRequestDTO.getSellStartDatetime()
            .isBefore(productRequestDTO.getSellEndDatetime())) {
            throw new BadRequestException(PRODUCT_VALIDATION_FAIL);
        }

        String name = productRequestDTO.getName();
        String result = name + "some default value";
        // productRequestDTO -> Product

        productPersistence.addProduct(productRequestDTO);
        productPersistence.addProductImages(productImages);
    }
```

2024-02-01 00:19 UTC, ka-MS commented on src/main/java/com/psj/itembrowser/product/service/impl/ProductServiceImpl.java
> +        }
dto ->product로 매핑하고 도메인 안에서 검증하는 메서드 작성하는 쪽으로 수정했습니다.

2024-02-04 15:17 UTC, merged