[PR] 주문 다건 조회 기능 구현 및 테스트 코드 작성
ITEM-BROWSER/ITEM-BROWSER pull request #8
Opened 2024-02-06 03:43 UTC by qkrtkdwns3410

1. 목표
-

2024-02-07 13:03 UTC, samuelmento requested changes
고생하셨습니다 ~!

2024-02-07 13:03 UTC, dev-mentoring commented on build.gradle
> +    testImplementation 'org.mockito:mockito-inline:4.5.1'
주석 남겨주실 내용이 // TODO JPA 전환되면 삭제 예정으로 남겨주세요

2024-02-07 13:03 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/controller/OrderApiController.java
> +        @CurrentUser Jwt jwt) {
개행 하지말고 한줄로 나타내주세요!

2024-02-07 13:03 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/controller/OrderApiController.java
> +        }
조건문에서 if , else if 로 끝나는건 별로 추천하지 않습니다.

else 다른 예외처리를 진행한다던가

2024-02-07 13:03 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/controller/OrderApiController.java
> +        return new MessageDTO(format("Order record for {0} has been deleted.", orderId));
개행해주세요!

2024-02-07 13:03 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/domain/dto/request/OrderPageRequestDTO.java
> +@EqualsAndHashCode(callSuper = true)
이 어노테이션은 왜 사용하는걸까요?

2024-02-07 13:03 UTC, dev-mentoring commented on src/main/java/com/psj/itembrowser/order/domain/dto/request/OrderPageRequestDTO.java
> +@EqualsAndHashCode(callSuper = true)
사용하지 않다면 삭제해도 좋을 것 같아요!

2024-02-07 13:03 UTC, samuelmento commented on src/main/java/com/psj/itembrowser/security/auth/service/impl/AuthenticationServiceImpl.java
> +            .getName();
유저 정보를 알고싶은데, 그럴때마 UserDetailsServiceImpl 이걸 의존해서 가져오는게 좀 찜찜하실텐데

어노테이션으로 빼는 기능을 써보신다면 코드가 훨씬 깔끔해질겁니다

2024-02-10 14:24 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/order/domain/dto/request/OrderPageRequestDTO.java
> +@EqualsAndHashCode(callSuper = true)
Equal + hashcode 메서드 생성을 위해서 추가했었습니다.
callSuper => true 의 경우, 슈퍼클래스의 필드까지 비교대상으로 삼지만, 그럴 이유는 없는 것 같아, 그냥 false 처리했습니다.

2024-02-10 14:25 UTC, qkrtkdwns3410 commented on src/main/java/com/psj/itembrowser/security/auth/service/impl/AuthenticationServiceImpl.java
> +            .getName();
어노테이션으로 Jwt 객체밖에 받지못하는 것 같습니다..
oauth2 resource 라이브러리 설정때문인거같네요..

그래서 그냥 컨트롤러에서 서비스까지 Member 객체를 전달해줬습니다.

2024-02-10 14:27 UTC, merged